version: '3.4'

services:
  frontend:
    build: 
      context: ./front
      network: host
      dockerfile: Dockerfile
    image: frontend
    container_name: frontcontainer
    command: npm start
    volumes:
      - ./front/:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: 
      context: ./back
      network: host
      dockerfile: Dockerfile
    image: backend
    container_name: backcontainer
    command: npm start
    volumes:
      - ./back/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3002:3002
    depends_on:
      - mongodb
  mongodb:
    image: mongo